# This workflow will automatically bump the version when changes are pushed to main
# See: https://github.com/marketplace/actions/automated-version-bump

name: Automated Version Bump

on:
    push:
        branches:
            - main

jobs:
    version-bump:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: phips28/gh-action-bump-version@v11.0.7
